### ISSUE TITLE
Pre-image received before new validator's information is saved in a block

### ISSUE THREAD

**Issue by linked0** [bosagora/agora#1166]
This problem appears in PR #1163 and in the middle of modifying the code of PR #1156 and only occurs in the network tests.

Suppose that one outsider(A) and an already enrolled validator(B) are being enrolled in a block for a new validator cycle.
When the outsider A is enrolled as a validator, it receives an pre-image of validator B before the new block having the information of the new enrollments is added into the chain. Technically, `receivedPreimage` from the validator B is called on A side before `addValidatedBlock` is called while the new block containing the new validators is being made on A side.

**Comment by AndrejMitrovic** [comment]
Ah so it's a timing issue.

- Block gets externalized
- Node A sends its new preimage based on the new enrollment in this block
- Node B receives the preimage **before** it receives the new block. The preimage is determined to be invalid
- Node B receives a new block. Finds the enrollment. Sets the distance to 0.

Then the question is how do we work around this?

I think this issue is very similar to https://github.com/bpfkorea/agora/issues/1082, except that one is about transactions.

**Comment by AndrejMitrovic** [comment]
Maybe a node should always periodically send its preimage?

Right now it only sends it **once** because of https://github.com/bpfkorea/agora/blob/489059625d38fbb6eac60687e42b46bb70bf5372/source/agora/node/Validator.d#L362

**Comment by linked0** [comment]
> Maybe a node should always periodically send its preimage?

Yeah, that would be a right and quick solution I think.
