### ISSUE TITLE
`Nominator.combineCandidate` can `throw`

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1210]
```
core.exception.AssertError@source/agora/consensus/protocol/Nominator.d(635): Assertion failure
----------------
/Users/geod24/dlang/dmd-2.094.0-beta.1/osx/bin/../../src/druntime/import/core/internal/array/equality.d:203 _ZN9Nominator17combineCandidatesEyRKSt3setIN3xdr7xvectorIhLj4294967292EEEE [0x10f9c53b5]
??:? _ZN7stellar18NominationProtocol15processEnvelopeERKNS_11SCPEnvelopeE [0x10fc0ce9e]
??:? _ZN7stellar4Slot15processEnvelopeERKNS_11SCPEnvelopeEb [0x10fc61603]
??:? _ZN7stellar18NominationProtocol14emitNominationEv [0x10fc0afaf]
??:? _ZN7stellar18NominationProtocol8nominateERKN3xdr7xvectorIhLj4294967292EEES5_b [0x10fc0dccd]
??:? _ZN7stellar4Slot8nominateERKN3xdr7xvectorIhLj4294967292EEES5_b [0x10fc6239c]
??:? _ZN7stellar3SCP8nominateEyRKN3xdr7xvectorIhLj4294967292EEES5_ [0x10fc50eec]
/Users/geod24/dlang/dmd-2.094.0-beta.1/osx/bin/../../src/druntime/import/core/internal/array/equality.d:203 @trusted void agora.consensus.protocol.Nominator.Nominator.nominate(ulong, agora.consensus.data.ConsensusData.ConsensusData) [0x10f9c48c8]
/Users/geod24/dlang/dmd-2.094.0-beta.1/osx/bin/../../src/druntime/import/core/internal/array/equality.d:203 @safe void agora.consensus.protocol.Nominator.Nominator.checkNominate() [0x10f9c4740]
submodules/localrest/source/geod24/LocalRest.d:373 void geod24.LocalRest.Timer.run() [0x10fd25135]
submodules/localrest/source/geod24/concurrency.d:916 void geod24.concurrency.FiberScheduler.create(void delegate()).wrap() [0x10fd26b84]
??:? void core.thread.context.Callable.opCall() [0x10ff10938]
??:? fiber_entryPoint [0x10ff0d09b]
??:? 0x0 [0xffffffffffffffff]
```

Seeing this error from time to time. `combineCandidate` has a `scope (failure) assert(0);` which is what the stack-trace points to. We should fix this so that we get a proper stack trace (and yes, the trace is rubbish).

Drey edit: The function should likely try/catch any Exceptions, log them, and then `assert(0);`. This way we will get the proper stack trace of the exception in the log.

**Comment by AndrejMitrovic** [comment]
> Seeing this error from time to time. 

Is it in v0.x.x or with the new SCP bindings?

**Comment by AndrejMitrovic** [comment]
Whoever tackles this issue should also be aware of https://github.com/bpfkorea/agora/issues/363. In fact we should probably fold issue #1210 into #363 because it would be nice to get proper stack traces in the logs everywhere.

**Comment by hewison-chris** [comment]
I am seeing this thrown in a test case I am currently writing. It happens about 1 in 3 runs of the test. Adding a try / catch and debug logging I found that it was due to no valid candidate in the provided candidates to combine:-

Running ./build/agora-unittests 
**combineCandidates: no valid candidate for slot 6**
#### FATAL ERROR: Assertion failure
This node was started at source/agora/test/EnrollmentManager.d:39
This most likely means that the node crashed due to an uncaught exception
If not, please file a bug at https://github.com/Geod24/localrest/
Full error: core.exception.AssertError@source/agora/consensus/protocol/Nominator.d(703): Assertion failure
----------------
??:? onAssertError [0x103b05430]
??:? _d_assert [0x103b05974]
??:? _ZN9Nominator17combineCandidatesEyRKSt3setIN3xdr7xvectorIhLj4294967292EEEE [0x102fbd441]
??:? _ZN7stellar18NominationProtocol15processEnvelopeERKNS_11SCPEnvelopeE [0x103549e2e]
??:? _ZN7stellar4Slot15processEnvelopeERKNS_11SCPEnvelopeEb [0x10359e593]
??:? _ZN7stellar18NominationProtocol14emitNominationEv [0x103547f3f]
??:? _ZN7stellar18NominationProtocol8nominateERKN3xdr7xvectorIhLj4294967292EEES5_b [0x10354ac5d]
??:? _ZN7stellar4Slot8nominateERKN3xdr7xvectorIhLj4294967292EEES5_b [0x10359f32c]
??:? _ZN7stellar3SCP8nominateEyRKN3xdr7xvectorIhLj4294967292EEES5_ [0x10358de7c]
??:? @trusted void agora.consensus.protocol.Nominator.Nominator.nominate(ulong, agora.consensus.data.ConsensusData.ConsensusData) [0x102fbe039]
??:? @safe void agora.consensus.protocol.Nominator.Nominator.checkNominate() [0x10308b858]
??:? void geod24.LocalRest.Timer.run() [0x103642d46]
??:? void geod24.concurrency.FiberScheduler.create(void delegate()).wrap() [0x103644ce8]
??:? void core.thread.context.Callable.opCall() [0x103b12b4e]
??:? void core.thread.fiber.Fiber.run() [0x103b12cdd]
??:? fiber_entryPoint [0x103b12c12]

**Comment by AndrejMitrovic** [comment]
Can you please push your changes which trigger the bug into a new branch so I can check it out locally?
