### ISSUE TITLE
Use genesis block (testnet / coinnet) from code rather than storing in config file.

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1244]
Currently each node loads the genesis block from a serialised hex string contained in the node's config.yaml. An improvement, suggested by @Geod24, is to use an enum in the config.yaml and load the correct genesis block from the binary executable.

**Comment by Geod24** [comment]
For reference, it doesn't have to be in the config. But we should guard against misuse. One such misuse is to use a mainnet key on testnet. Another is doing some testing with a node, then restarting it to be on Mainnet, but not wiping out the cache.

**Comment by hewison-chris** [comment]
How about we use a folder name for each network. For example:
mainnet/config.yaml
mainnet/.cache

testnet/config.yaml
testnet/.cache

**Comment by Geod24** [comment]
That would work indeed. But also, having different keys gives us free replay protection.

**Comment by hewison-chris** [comment]
Yes each config.yaml has a different GenesisBlock.

**Comment by Geod24** [comment]
What I mean is that, if the keys have the same values, you could end up accidentally using the same key on both network.
That's why most blockchains have [this scheme](https://support.bitpay.com/hc/en-us/articles/360004102011-What-is-testnet-How-do-I-avoid-testnet-Bitcoin-scams-#:~:text=All%20bitcoin%20testnet%20addresses%20begin,and%20either%20p%20or%20q.).
