### ISSUE TITLE
Change registries (network, test) to use the UTXO instead of the public key

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1309]
Spin off from #849

As discussed, public keys are not currently unique, while utxo will always be. When referring the nodes individually, we should then use the UTXO instead of the public key. This will allow to prevent mishap if someone ever does something funny with enrollments.

**Comment by Geod24** [comment]
After discussing with @linked0 , it seems that the network test doesn't really need to change because it's not using the public key currently, but a custom string.

**Comment by linked0** [comment]
```
public struct QuorumConfig
{
    /// Threshold of this quorum set
    public uint threshold = 1;

    /// List of nodes in this quorum
    public PublicKey[] nodes;

    /// List of any sub-quorums
    public QuorumConfig[] quorums;
}
```
As discussed in the last Sprint Update, we should change the type of `nodes` into `Hash[]` because we need to identify nodes by the hash of a UTXO instead of a PublicKey. And also need to change the following line in `Stellar_types.d` into using Hash instead of PublicKey.
```
alias NodeID = PublicKey;
```

@Geod24 What do you think of it? Could you leave some comment if it's not right?

**Comment by Geod24** [comment]
Sounds right
