### ISSUE TITLE
Agora keeps sending pre-images to Stoa

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1322]
I'm seeing this in Stoa's log after fixing bpfk/stoa#164:

```
Nov 04 06:28:38 eu-002 docker[8094]: [Stoa] 2020-11-04T06:28:38.960Z info Saved a pre-image enroll_key : 0xdb3931bd87d2cea0, hash : 0xbb10e5050a2d0acd, distance : 6
Nov 04 06:28:44 eu-002 docker[8094]: [Stoa] 2020-11-04T06:28:44.975Z info Saved a pre-image enroll_key : 0xb20da9cfbda971f3, hash : 0x7b78dd8534d0b964, distance : 6
Nov 04 06:28:48 eu-002 docker[8094]: [Stoa] 2020-11-04T06:28:48.966Z info Saved a pre-image enroll_key : 0xdb3931bd87d2cea0, hash : 0xbb10e5050a2d0acd, distance : 6
Nov 04 06:28:54 eu-002 docker[8094]: [Stoa] 2020-11-04T06:28:54.975Z info Saved a pre-image enroll_key : 0xb20da9cfbda971f3, hash : 0x7b78dd8534d0b964, distance : 6
Nov 04 06:28:58 eu-002 docker[8094]: [Stoa] 2020-11-04T06:28:58.962Z info Saved a pre-image enroll_key : 0xdb3931bd87d2cea0, hash : 0xbb10e5050a2d0acd, distance : 6
Nov 04 06:29:04 eu-002 docker[8094]: [Stoa] 2020-11-04T06:29:04.973Z info Saved a pre-image enroll_key : 0xb20da9cfbda971f3, hash : 0x7b78dd8534d0b964, distance : 6
Nov 04 06:29:08 eu-002 docker[8094]: [Stoa] 2020-11-04T06:29:08.962Z info Saved a pre-image enroll_key : 0xdb3931bd87d2cea0, hash : 0xbb10e5050a2d0acd, distance : 6
```

**Comment by TrustHenry** [comment]
@Geod24 Are you aware of any doubts about this issue?
I tried debugging, but I can't find the exact cause.

**Comment by Geod24** [comment]
I can still see it happening in the live system, yes.

**Comment by linked0** [comment]
This issue is caused by constantly sending a pre-image in the function 'checkRevealPreimage' of the `Validator`. The reason why it keeps sending it constantly is that there might be some nodes not having pre-images due to some reason like a network outage. But, it can be changed to not sending the pre-image if it's present in the `ValidatorSet` as follows. In fact, the `getValidatorPreimageAt` is not implemented yet. But it could be implemented by just calling the `getPreimageAt` function of the `ValidatorSet`. 

```
private void checkRevealPreimage () @safe
{
    PreImageInfo preimage;
    if (!this.enroll_man.getValidatorPreimageAt(this.ledger.getBlockHeight() + 1) && 
        this.enroll_man.getNextPreimage(preimage, this.ledger.getBlockHeight()))
    {
        this.enroll_man.addPreimage(preimage);
        this.network.sendPreimage(preimage);
        this.pushPreImage(preimage);
    }
}
```

Sorry for the late notice on this issue.
@TrustHenry Could we have a whiteboarding session at your desk or mine?

**Comment by linked0** [comment]
But, there are some points we need to check if the solution I described breaks test codes and whether it's right to send pre-image once the same way as sending a transaction.

**Comment by Geod24** [comment]
> The reason why it keeps sending it constantly is that there might be some nodes not having pre-images due to some reason like a network outage.

But why does it keep sending to Stoa ?
I guess we could also handle it on the Stoa side and make it ignore already-received pre-image (and other data).

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/stoa/blob/485a7f6a0b7c79821fa5374c8e8e2a848f88ccd1/src/modules/storage/LedgerStorage.ts#L352-L367
When updating the image of Stoa, the distance must be greater than the current value.
It ignore anything else.
However, in this case, the message is also marked as saved.

**Comment by Geod24** [comment]
> However, in this case, the message is also marked as saved.

Then maybe we should do the sane thing and only output a message on update at `info` level... We can still output all http traffic at `http` level.

**Comment by MichaelKim20** [comment]
There are two agora in the live system.
Doesn't it seem like the pre-image is transmitting a lot because both of these agora send a pre-image?

**Comment by linked0** [comment]
I think we should maintain the feature a validator keeps sending pre-images because the situation where pre-images of validators are missing is very critical. This issue could lessen if we set the `preimage_reveal_interval` to a larger value like 30 seconds in the `faucet` live system. And this issue has already been worked around by @TrustHenry in [the PR](https://github.com/bpfkorea/stoa/pull/208). 
So this issue could be closed in the current state, I think.

**Comment by TrustHenry** [comment]
> I think we should maintain the feature a validator keeps sending pre-images because the situation where pre-images of validators are missing is very critical. This issue could lessen if we set the `preimage_reveal_interval` to a larger value like 30 seconds in the `faucet` live system. And this issue has already been worked around by @TrustHenry in [the PR](https://github.com/bpfkorea/stoa/pull/208).
> So this issue could be closed in the current state, I think.

@Geod24 ping

**Comment by TrustHenry** [comment]
@Geod24 Do you think this issue has been resolved?

**Comment by Geod24** [comment]
We're blocked on Stoa working to actually test this.

**Comment by kchulj** [comment]
Stoa is unblocked.

**Comment by Geod24** [comment]
Looks like this is solved.
