### ISSUE TITLE
Hashing vulnerability with arrays

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1331]
Our current hashing algorithm suffers from a vulnerability:

```D
unittest
{
    static struct S
    {
        int[] arr1;
        int[] arr2;
    }

    auto s1 = S([1], null);
    auto s2 = S(null, [1]);
    assert(s1.hashFull() != s2.hashFull());  // fails
}
```

By default an array will not be hashed if its length is empty. But that can lead to cases like the above where two structures with completely different contents may end up hashing the same.

The issue can be much more subtle than this, especially when the struct embeds other structs which may themselves contain arrays.

**Comment by Geod24** [comment]
Do you know if any structure is affected ?

**Comment by AndrejMitrovic** [comment]
Not currently. But while experimenting with adding fields I've noticed this behavior.

We can of course try to be very careful when designing the structs. But I think we should probably try to solve this automatically.

One way to do it is to always hash the length of each array before its contents. It does increase the total amount of hash ops we would do though..

**Comment by omerfirmak** [comment]
> One way to do it is to always hash the length of each array before its contents. It does increase the total amount of hash ops we would do though..

This might be the only way to do it properly.

Do we care about the different typed objects having exact same byte patterns and evaluating to the same hash?

**Comment by Geod24** [comment]
> This might be the only way to do it properly.

Sounds good. It makes sense IMO to look at it from the deserialization  PoV: If it's ambiguous it's a hashing vulnerability. I don't think we have places where we hash structs containing pointers too, but if we did, we would need to encode a special value for `null`.

**Comment by ferencdg** [comment]
actually this problem doesn't just happens when 'null' is involved
```D
auto s1 = S([1,2], [3]);
auto s2 = S([1], [2,3]);
```
will also produce the same hash. Fortunately hashing the array size will solve this problem as well.

My main concern is that I see tests like this for hashing:
```D
    Hash foo = hashFull("foo");
    Hash bar = hashFull("bar");

    const merged = Hash(
        "0xe0343d063b14c52630563ec81b0f91a84ddb05f2cf05a2e4330ddc79bd3a06e57" ~
        "c2e756f276c112342ff1d6f1e74d05bdb9bf880abd74a2e512654e12d171a74");

    assert(hashMulti(foo, bar) == merged);

    const Hash[2] array = [foo, bar];
    assert(hashFull(array[]) == merged);
```
That means there was an expectation that the hash of an array of X elements is the same as the hashing those X elements sequentially. This property will no longer be true if we hash the size of the array too. If many of our code relied on this behaviour, then it will take a long time to change.

**Comment by ferencdg** [comment]
> > This might be the only way to do it properly.
> 
> Sounds good. It makes sense IMO to look at it from the deserialization PoV: If it's ambiguous it's a hashing vulnerability. I don't think we have places where we hash structs containing pointers too, but if we did, we would need to encode a special value for `null`.

This was my worry too that if our hash function could handle classes(or pointers) then we would have hash collisions like
```D
static struct S
{
    C c1;
    C c2;
}

auto s1 = S(new C(1), null);
auto s2 = S(null, new C(1));
```

and now we couldn't use the trick of 'array size' as we dont have arrays... However our hash function implementation currently doesn't work with classes or (structs that have classes). Hash function implementation also doesn't work with pointers currently.

**Comment by hewison-chris** [comment]
After discussion with @Geod24 we are considering hashing serialized data rather than binary. The advantage is that hash collisions would be much more unlikely and we would not need to move away from a well known RFC spec [referenced here in the code](https://github.com/bpfkorea/agora/blob/078df5bca11bdd5041d8b02c7b97fa9df38d7c01/source/agora/common/Hash.d#L195). This would mean that others that need to Hash with the same results would be able to use that spec also. If we hash the length of arrays then hash collisions are quite likely where zero length strings, byte arrays and other arrays would result in matching hash results from different structures. The overhead of the serialization should not be that big and each part to be hashed in [HashFull](https://github.com/bpfkorea/agora/blob/078df5bca11bdd5041d8b02c7b97fa9df38d7c01/source/agora/common/Hash.d#L113) can be serialized using the existsing [serializePart in the code here](https://github.com/bpfkorea/agora/blob/078df5bca11bdd5041d8b02c7b97fa9df38d7c01/source/agora/common/Serializer.d#L406).
Any opinions or objections to this approach?

**Comment by AndrejMitrovic** [comment]
That could work.

My only worry is that if we ever come up with a better serialization layout (e.g. something which uses less space), it will break hashing. But one could argue changing the serialization is breaking the API anyway, so it might be a moot point.

**Comment by AndrejMitrovic** [comment]
There are other benefits to using the serializer: It's designed (or well, intended) to be platform-agnostic.

**Comment by AndrejMitrovic** [comment]
Drawback: Hashing will be costlier w.r.t. CPU cycles.

**Comment by hewison-chris** [comment]
Currently blocked by https://github.com/bpfkorea/crypto/pull/4

**Comment by hewison-chris** [comment]
Unblocked now as bpfkorea/crypto#4 has been merged.
