### ISSUE TITLE
Implement transaction fee collection

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1435]
In order to support transaction replacement via bigger fees (https://github.com/bpfkorea/agora/issues/245), we also need to implement fee collection first.

Each transaction's fee is defined as the `Sum(Inputs) – Sum(Outputs)`.

In Bitcoin, **collecting** the fees is simple. The single miner which mined the block generates a `Coinbase` transaction which includes all of the transactions' combined fees and outputs them all to the miner's desired public key.

In our case, it's different. We don't have miners, we have consensus nodes. Therefore the fee needs to be distributed among the validator nodes. There are some open questions:

- How are the fees distributed among the nodes? Are they distributed evenly towards all (non-slashed) validators? Or does distribution depend on other factors such as: stake amount, number of total externalized Enrollments for that node..?
- After fee distribution is decided how do we update the UTXO set? In Bitcoin they use the Coinbase transaction for this. Do we need something similar? Or could we make it implicit in the protocol and not add any additional transactions to the block? If it's implicit then after externalization the UTXO set would need to be automatically updated to add new UTXOs to each validator node (the fees). But we need to be careful here because we're creating UTXOs from thin air basically. Maybe a Coinbase transaction would still be a better option.

**Comment by omerfirmak** [comment]
I think Coinbase transactions are way to go, implicitly generating UTXOs is too error-prone.

The problem is that this may not scale as the network grows. Potentially thousands of Validators could be enrolled each block. If we pay the fees for each Validator every block this would create a lot of bloat. Thousands of Coinbase transactions with very small amounts of coin, every block.

What do you think of paying the fees of a Validator at the end of it's cycle? Fees that would be paid to a Validator is accumulated and paid in a single Coinbase transaction on the last Block they are enrolled. We would make it a part of the protocol/block validation so that the Coinbase transactions would not be voted off in consensus.

Any opinions?

**Comment by AndrejMitrovic** [comment]
You raise excellent points. I fully agree, once per validator cycle would be ideal.

**Comment by AndrejMitrovic** [comment]
However with the CoinBase approach there is an issue that there's more data that needs to be kept in the block and sent over the network. That's why I suggested making it implicit might be better in terms of saving costs on total block storage size. Then again the total amount of outputs in Coinbase wouldn't necessarily be that big. Let me know what you think.

**Comment by omerfirmak** [comment]
> However with the CoinBase approach there is an issue that there's more data that needs to be kept in the block and sent over the network. That's why I suggested making it implicit might be better in terms of saving costs on total block storage size. Then again the total amount of outputs in Coinbase wouldn't necessarily be that big. Let me know what you think.

Yep, there is that. But with 1008 blocks validator cycle, on average, we would have 1 coinbase tx for every 1000 Validators per block. Probably negligible. But I would sugggest that we take the easier and probably safer route of using Coinbase TX for now. We can later evaluate the overhead in TestNet?

**Comment by AndrejMitrovic** [comment]
Sure. Then I think coinbase is the right first approach.

**Comment by omerfirmak** [comment]
> How are the fees distributed among the nodes?

~~About this, I am thinking of initial implementation to be purely stake amount based. But there could be cases where the total fee can't be divided properly.~~ 

~~Simplest example is distributing 5 BOA among 4 Validators with equal stake. The process should be both fair to all Validators and  should probably be deterministic to simplify the validation process. Even if we factor in additional stuff, we still might end up in a state where multiple nodes have exact same priority.~~

~~I noticed the `CommonsBudgetAddress`, could we use this to deposit the change BOA we can't easily distribute among Validators?~~

Turns out, this is already well defined in the white paper.

**Comment by ferencdg** [comment]
> Even if we factor in additional stuff, we still might end up in a state where multiple nodes have exact same priority.

In theory this shouldn't be a problem for example we could just look at the hash of the previous block as a random number and then we would distribute extra coins to validators in the following way: first the validator with the smallest public key hash gets the coin, however his public key hash has to be greater than the 'random' number of the previous block hash. (we need this random number because we don't want attackers pregenerate keys with the lowest possible public key hash to have a high chance of getting the extra coins)

I am not saying we should do this, your idea of distributing extra coins to CommonsBudgetAddress sounds better

**Comment by AndrejMitrovic** [comment]
Sending the remainder to the commons budget sounds better to me too.

**Comment by omerfirmak** [comment]
Data fees are currently expected to be paid by the wallet in each transaction.

https://github.com/bpfkorea/agora/pull/1368
https://github.com/bpfkorea/agora/pull/1321

As far as I can see, these PRs dont follow what white paper defines, in terms of the 70/30 split between validators and commons budget. Also, do we really want the wallet to explicitly create the payment output to commons budget? Transfers to commons budget could very well be done with a single Coinbase TX per block, saving a bunch of space in a block. Also this makes the wallet implementation more complex too, all the edge cases we will cover in the Validator, like the ones mentioned in this issue, would be replicated in the wallet too.

**Comment by AndrejMitrovic** [comment]
> Transfers to commons budget could very well be done with a single Coinbase TX per block, saving a bunch of space in a block. Also this makes the wallet implementation more complex too, all the edge cases we will cover in the Validator, like the ones mentioned in this issue, would be replicated in the wallet too.

You mean the coinbase idea would make the wallet implementation more complex, or the current implementation is making it more complex?

In general I agree that collecting all the fees into the commons budget is not ideal. Because then nobody is paying the validators for the storage fee. So there is very little incentive of actually wanting to include such a transaction in the block. But I'm not sure if the c-level wants to change this (when I say c-level I am excluding the CTO). It was their executive decision that the entirety of the data payload fee has to be sent to the commons budget.

**Comment by omerfirmak** [comment]
> You mean the coinbase idea would make the wallet implementation more complex, or the current implementation is making it more complex?

I was talkıng about the existing implementation making the wallet more complex, because it would need to handle the 70/30 split as well. But since the data fees would all go to the commons budget, wallet may not be any more complex.

What is your take on not including commons budget outputs in each tx with payload? Instead we would just create one Coinbase TX per block, that would pay all the data fees and the %30 from the regular tx fees.

**Comment by AndrejMitrovic** [comment]
It sounds good to me if we can make the wallet less complex.

**Comment by omerfirmak** [comment]
On the side note, paying each Validator at the end of their cycle requires the ability to get a list of Validators of any Block in the past. Without any additions to the existing code, I think, only way to do this is walk the entire chain. We have to walk the entire chain because we don't have a maximum value defined for validator cycles yet.

We could either store this information in ValidatorSet or could we extract it from the block signatures that was just implemented? :)

**Comment by AndrejMitrovic** [comment]
What do you mean "entire chain"? You only have to walk back N blocks, where n is the [cycle length](https://github.com/bpfkorea/agora/blob/d20a786612837a5ea06ea4ebc90f3081f43bf0c4/source/agora/consensus/data/Enrollment.d#L46) for that validator. Unless I misunderstood your question?

**Comment by omerfirmak** [comment]
So, we are at block height `H` and Validator #0's cycle of `N` blocks is about to end. 

We need to calculate the fees for Validator #0 in Block `H-N` to Block `H`. For every block in this range, we would need to know the other Validators that are active on that height and their stake amount. Validator set for each block could be different. 

To get a Validator set of Block height `K` there is no other way than checking enrollments of all the blocks up to `K`. Since they could've been enrolled in any point. If we had an upper bound for `cycle_length` we would need to scan starting from Block `K - max_cycle_length`and going upward.

Hope that makes sense.

**Comment by AndrejMitrovic** [comment]
Since currently the cycle length (or max cycle length) is set in the consensus params, you could get away with just always keeping the list of active validators per block for the last 1008 blocks. So current height - 1008.

Of course if we allowed custom cycle lengths then it's a bit different. 

In any case I think we would need to come up with an efficient data structure to keep track of the active validators.

**Comment by MichaelKim20** [comment]
The white paper describes the transaction fee as follows the transaction fee.
Transaction Fee: The transaction fee is a fixed 0.01 BOA. Congress Nodes receive
70% of the collected transactions fee in a block, and 30% is sent to the Commons
Budget. Transaction fees can be adjusted through the Congress.

**Comment by Geod24** [comment]
@omerfirmak 's points are excellent (and I think we already discussed this):
1) Distribution needs to be periodic, not with every block;
2) Said fee should be derived directly from the protocol, so everyone with the same history will reach the same transaction;

> Data fees are currently expected to be paid by the wallet in each transaction.

[Source](https://github.com/bpfkorea/agora/issues/1435#issuecomment-749437070).
Data fee are different. They are additional fees (on top of the tx fee), and don't follow the same rules. The only relationship they have is that they are minored by the tx fee (at least that was the original idea).

**Comment by Geod24** [comment]
Note that my original idea was to distribute every X blocks (with X = 144 for example, aka 1 day) so that everyone is paid at the same time. As we want a stale network, keeping validators on as long as possible is desirable, hence we should be careful not to influence them into having shorter cycles so that the payout is more frequent.

**Comment by omerfirmak** [comment]
> @omerfirmak 's points are excellent (and I think we already discussed this):
> 
>     1. Distribution needs to be periodic, not with every block;
> 
>     2. Said fee should be derived directly from the protocol, so everyone with the same history will reach the same transaction;
> 
> 
> > Data fees are currently expected to be paid by the wallet in each transaction.
> 
> [Source](https://github.com/bpfkorea/agora/issues/1435#issuecomment-749437070).
> Data fee are different. They are additional fees (on top of the tx fee), and don't follow the same rules. The only relationship they have is that they are minored by the tx fee (at least that was the original idea).

So, do we keep the per-TX output to the commons budget? For the data fees.

Alternative, which I have already implemented, is to create a single Coinbase TX in each block to pay the data fees + the tx fee cut that the commons budget would get.

**Comment by omerfirmak** [comment]
> Note that my original idea was to distribute every X blocks (with X = 144 for example, aka 1 day) so that everyone is paid at the same time. As we want a stale network, keeping validators on as long as possible is desirable, hence we should be careful not to influence them into having shorter cycles so that the payout is more frequent.

With this, every Xth block will probably be larger than the other blocks. This could become significant with a large number of Validators.
