### ISSUE TITLE
Nodes should be able to recover from exhausting their PreImageCycle

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#1500]
Once the preimages in a `PreImageCycle` are all used, nodes can't enroll again with the same UTXO.
They should be able to transfer their staked coins to a new UTXO, generate a new cycle of preimages and start enrolling with it.

This should probably be enabled by the `recurring_enrollment` config or a new one.

**Comment by linked0** [comment]
We can re-generate new preimages with this code. 

https://github.com/bpfkorea/agora/blob/0fdda867e11f2f3fc9eb68a79586a5ff6af39a1d/source/agora/consensus/PreImage.d#L358-L364

When a bulk of pre-images like 100800 of preimages has been all used, we can increase the `nonce` and set the `index` to zero, and we can generate 100800 of preimages again. What makes you think that we can not enroll again with the same UTXO?

**Comment by omerfirmak** [comment]
Since #1421 is merged, that would not work. After all generated preimages are used, you would need to enroll again with -1th preimage. Which does not exist :)

**Comment by linked0** [comment]
Making a new UTXO for generating preimages is not the right way. I think the use of increasing `nonce` should be restored.

**Comment by omerfirmak** [comment]
This was discussed on https://github.com/bpfkorea/agora/issues/1297 and the need for a new UTXO was a known trade-off.

**Comment by hewison-chris** [comment]
As this prevents our production nodes running beyond block 1999 I would like to resolve this issue this sprint. 
Of course we first need to examine the options and then agree on what our solution will be.

**Comment by hewison-chris** [comment]
The team discussed this issue at the Sprint planning and it was decided that the number of Pre-Images generated when first enrolling should be large enough that there would unlikely be the need to ever re-enroll with a new preImage seed. This number should be a consensus parameter that in production could be set to say 5 million so that it can run, assuming a block every 10 minutes, for over 90 years without need to create a chain of preImages from a new seed. In testing, where we often generate blocks at a shorter time interval, we can ovveride this value in the config if needed.
This means that the [offset](https://github.com/bpfkorea/agora/blob/fef3a5eeff99d42835cba43b0087fbfc6ba8f1ca/source/agora/consensus/EnrollmentManager.d#L469) that it currently used to generate the signature noise for the enrollement could be removed, as it will always be zero. 
Also [nonce here](https://github.com/bpfkorea/agora/blob/fef3a5eeff99d42835cba43b0087fbfc6ba8f1ca/source/agora/consensus/PreImage.d#L296) will no longer be needed.

**Comment by hewison-chris** [comment]
Creating 5 million pre-images takes less than a second so I think we can now make it a fixed value in the code rather than a `consensus param`.
Also as @Geod24 mentioned the `number_of_cycles` is no longer required as we just have a value for the number of `preImages` to generate.

**Comment by hewison-chris** [comment]
Another solution to consider might be to allow the end user to decide how many `pre-images` he wants to generate with his UTXO (config option). 
We could store this in the `preimageCycle` so that the `pre-image` for a certain height is calculated correctly. When he runs out of preimages his validator will no longer be able to enrol so his UTXO could be melted when this limit is reached.
If he wants to enrol his `validator` again he needs to update his config with a higher number of `preimages` than the last time so that he can enrol at higher heights.

**Comment by linked0** [comment]
Good idea, but we have to store permanently somewhere the number of the pre-images set to each UTXO, which is how many pre-images he wants to generate for a specific UTXO. Considering the catchup process makes us think about it.

**Comment by Geod24** [comment]
Fixed by #2291
