### ISSUE TITLE
Flash Layer: Network topology in-memory representation

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#1583]
This is a sub issue of #1528 

Problem of routing a payment through lightning network is essentially a graph problem. We should have an efficient in-memory representation of the network that a Lightning Node is aware of. So that we can traverse and build paths along the network efficiently.

**Comment by omerfirmak** [comment]
Well, there is no branch that I can open a PR against. So, [this](https://github.com/omerfirmak/agora/commit/70dbce335be9b3f97b8a673dc5ba8bec982ece8e) commit implements the basic network representation. Once the flash layer work of @AndrejMitrovic is fully merged and channel fee stuff are implemented, we can easily integrate this to implement "path probing".

**Comment by AndrejMitrovic** [comment]
I will get my work ready for merging soon!

**Comment by omerfirmak** [comment]
> I will get my work ready for merging soon!

Is there anything I can help with?

**Comment by AndrejMitrovic** [comment]
Figuring out why the `flash-layer` branch times out and fixing it would unblock the work. Because until it's fixed we won't be able to merge all the code changes to `v0.x.x`

**Comment by AndrejMitrovic** [comment]
Here's the latest state: https://github.com/AndrejMitrovic/agora/tree/multi-hop

It's based on `flash-layer-v3` (https://github.com/bpfkorea/agora/pull/1579) which times out, most probably due to heavy usage of the GC.

Basic multi-hop payments work. Although I haven't properly implemented secret sharing. Currently in an `A => B => C` channel configuration the `B + C` channel will have the HTLCs properly folded, but `A => B` will not as I haven't implemented sharing the secret back to the originator of the payment.

There's still plenty of work that needs to be done here. And the retry mechanism isn't great. If you want to play with it:

```
dchatty=true dnologs=true dtest=agora.test.Flash dub test
```

**Comment by omerfirmak** [comment]
It seems like we are missing 2 components right now to integrate this into @AndrejMitrovic's work.

First is Flash node discovery. If we want to be able to gossip certain events in the Lightning Network, Flash nodes should probably make themselves known. I could not see anything related to this in the `multi-hop` branch, correct me if I am wrong.

Second is, like @AndrejMitrovic have already [mentioned](https://github.com/bpfkorea/agora/issues/1528#issuecomment-766614815), with the information we get from node discovery we should at least gossip open channels. Without that, nodes have no idea about open channels that they are not a part of. There is no reliable way to get this information from the chain, right?

**Comment by AndrejMitrovic** [comment]
> I could not see anything related to this in the multi-hop branch, correct me if I am wrong.

I'll add simple node discovery now by just adding another gossiping end-point. I fixed secret sharing so I can focus on this now.

> There is no reliable way to get this information from the chain, right?

The only info from the chain is the funding tx hash (this is where the channel's unique ID is derived from), and the Schnorr key lock. But we cannot extract individual public keys from this contract on-chain.

So yes, gossiping needs to be implemented. Since I need it to pass my test-suite I'll add a simple implementation to my branch.

**Comment by AndrejMitrovic** [comment]
I just implemented very basic path finding. Well, the algorithm itself doesn't actually work if there are more than 2 channels. I needed to just make sure it works.

I just need to clean up the tests a bit and then I will submit a PR soon.

**Comment by AndrejMitrovic** [comment]
Oh and gossiping is done too.

**Comment by omerfirmak** [comment]
Fixed in #1611
