### ISSUE TITLE
Remove usage of crypto's `multiSigSign `, `multiSigVerify` and use `sign` / `verify`

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1642]
This should be a low hanging fruit. Currently we have some duplication in the crypto module.
This makes the code harder to audit and to reason about. If the `sign` / `verify` functions don't expose the required primitives, they should be broken down like `sign` was, with its multiple APIs which offer different levels of convenience.

From a quick look, `sign` can already replace `multiSigSign`, but `verify` might need to be split.

**Comment by hewison-chris** [comment]
Turns out `sign` can not be swapped for `multiSigSign` because then we can only verify when all signers sign. This means we can not verify each individual signature or any combination of the signing group's signatures. The main issue is that R in `multiSigSign` is not the sum of all R's but the sum of included R's.
