### ISSUE TITLE
Test `agora.test.ValidatorRecurringEnrollment` is sleep-bound (4m15s)

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1977]
```
2021-04-18T11:56:18.2318560Z Unittesting agora.test.ValidatorRecurringEnrollment..
2021-04-18T12:00:03.9434600Z Unittesting agora.test.ValidatorCount..
```

This is 4m15s of run time on MacOSX, which is 33% of the CI run time on a good day (less on a bad day).
It takes almost the same time on Ubuntu, which leads me to believe that it's not due to the inherent complexity.

**Comment by linked0** [comment]
After having analyzed the test and other unit tests, the most time-consuming function call turns out to be the `expectHeight` which spends about 400 milli-secs on my local machine which could be 2 times faster than the CI. And the function is called 834 times in all the unit tests and the total time for all the unit tests is 5~6 minutes which accounts for 40% of the total running time. I will find the way we could call the function more efficiently like decreasing the count of calling the function or calling the function with fewer target nodes.
