### ISSUE TITLE
Ensure that validators sign with a frozen UTXO

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#205]
As a developer, I need to make sure that signatures by validators are done using a frozen UTXO in order to make sure the validator has stake in the system.

**Definition of Done:**
- [x] There is a way to link a signature and a frozen UTXO

**Comment by Geod24** [comment]
Depends on #204

**Comment by bpalaggi** [comment]
Depends on #209

**Comment by Geod24** [comment]
Unblocked

**Comment by TrustHenry** [comment]
> I need to make sure that signatures by validators are done using a frozen UTXO in order to make sure the validator has stake in the system.

Where signature by Validators means signature of BlockHeader or `enrollment.S` ?
Does frozen UTXO check the UTXO of the enrollment K (UTXO key) ?

**Comment by Geod24** [comment]
> Where signature by Validators means signature of BlockHeader 

Yes

> Does frozen UTXO check the UTXO of the enrollment K (UTXO key) ?

That's a different issue

**Comment by TrustHenry** [comment]
When a block is received or signed
Validators signed BitField...
The frozen UTXO shall be found and verified in utxo_db?

**Comment by AndrejMitrovic** [comment]
This issue #205 only deals with the validation part of a block.

So if we have a block header which is signed, in order to validate the block then the signature must be checked. We need to make sure:
- The signature is actually valid.
- The key it was signed with belongs to a node that has frozen 40,000 Boa. If the node hasn't frozen 40,000 Boa then it has no right to sign the block, therefore the block is invalid.
- The height of the block that contains the signature of a node, it must be at least N blocks after the block height where the node staked 40,000 Boa. The "N" is defined in the Yellow paper. So, a node first freezes UTXO, then after N blocks it can start signing blocks.
- If the UTXOs for that node are actually melting, the signature is considered invalid.

I suggest implementing this issue #205 in several **steps**, depending on what kind of approach you want to take:
- At first, assume the block header can only contain one validator signature. This makes it easy to implement the checks for the frozen UTXO. You could just store a `PublicKey validator; Signature signature;` in the block header, and change `isInvalidReason` for blocks so that it tests the conditions that I listed in the previous paragraph (see also the Definition of Done).
- Then, if that works, try to extend your function so it works with multiple signatures. For example, you could write `struct ValidatorSigs { PublicKey key; Signature sig; }` and add that to the block header `struct BlockHeader { ValidatorSigs[] validator_sigs; }`. For example, all the signatures in the block header must be valid. As soon as one is invalid, the block is rejected.

Then later, once https://github.com/bpfkorea/agora/issues/365 and https://github.com/bpfkorea/agora/issues/406 are implemented, we can adapt your solution and change the block header so it works with the Schnorr signature scheme and with the Enrollment process.

If that doesn't help, I can only suggest waiting for input from @Geod24.

**Comment by TrustHenry** [comment]
>  A melting UTXO cannot sign blocks

~~a melting UTXO cannot sign blocks" The requirements should be deleted.~~

Frozen UTXO can sign the block as a validator up to the "freezing period / 2" block during the transaction occurring and melting period.

**Comment by TrustHenry** [comment]
ping @Geod24
