### ISSUE TITLE
Flash payment shouldn't rely on the availability of some central servers

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2292]
This issue is inspired by https://github.com/bosagora/agora/issues/2289

After talking to Omer, it turns out the flash layer payments are depending on the availability of some central servers(called registries). To make things worse, they might depend on 1 single sever. That means if there is any unexpected issue like hardware failure, then the flash layer might not work as expected. This is similar to the Paypal solution that relies on central servers to function correctly.

The solution to the problem above is **not** to make those central servers DoS resistant(in my opinion). Does the bitcoin flash layer use central servers, the way we use?

**Comment by Geod24** [comment]
> This is similar to the Paypal solution that relies on central servers to function correctly.

There is a very important difference that might be missed here. Having a central server isn't a problem. Having an authoritative server is. Paypal is an authoritative server, because not only can't you run your own "paypal node", but the validity of the data depends on the *origin* of the data.

On the other hand, name registry can be replicated and the data it contains has been signed by a key, so it can't even create fake data. At worst, an attacker can:
- Withhold data;
- Provide outdated data;

But in the presence of at least one honest registry, this issue will be easily solved.

I agree that the situation isn't ideal, and we should explore ways to reduce reliance on it. And if you happen to have some suggestions as well, we should explore them (let's have a whiteboard about it). However, I don't think the current situation is an essential blocker for, e.g. CoinNet.

**Comment by ferencdg** [comment]
I would disagree.

from what I deduced from a conversation with Omer(and I mentioned it here) is that currently ALL flash nodes would store information on the SAME server instance (I suppose if they use different instances, then they cannot share information). That is most probably will be run by Bosagora, that is more than centralized. Maybe the information can be stored simultaniously in multiple Registry entries, but as long as it is a limited number of servers DDoS attacks are possible (at the very minimum they have to be behind a cloudflare protection). Also creating a decentralized system like crypto payment with unnecesseary central entitites like Registry is a big architectural mistake. I doubt Bitcoin uses centralized entites for flash payments. 

Just want to say it for the record that in my opinion this all Registry idea was a mistake, but of course I can try to make it more DoS resistant.

An additional problem is how will the registry know which flash nodes are allowed to register any data into the registry, it is not like that flash nodes enroll, so I don't know which public keys are allowed. Your idea of solving this?

**Comment by Geod24** [comment]
Turning the registry into a DNS server, as done in #2392 , solves the issue.
