### ISSUE TITLE
Reduce pre-image flood

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2356]
We currently take a rather aggressive approach to pre-image propagation (read: we just send it, all the time), which leads to a lot of unnecessary traffic. We should remember which nodes received the pre-images and prevent flooding them.

**Comment by linked0** [comment]
We could start implementation by applying the table called `preimage_revelation` in the `ValidatorSet` class as follows.

`
CREATE TABLE IF NOT EXISTS preimage_revelation (enrollment_key TEXT, peer_pk TEXT, revealed_height INTEGER) PRIMARY KEY (enrollment_key, peer_pk), CHECK (revealed_height >= 0)
`
When the callback of the preimage revelation timer is called, a validator only reveals pre-images to peers that have a lower `revealed_height` than the height of preimages it is about to reveal.

The above design is not a complete solution, but just an initial design and a feature to implement first.

@Geod24 You said this issue is kind of a big issue. There are other points to consider that I will summarize soon. Please tell me your opinion on this issue at any time.

**Comment by linked0** [comment]
After analyzing the Agora code, I determined that creating a table for revealed preimages described in the above comment is not a right solution.

Instead, we can hold an associative array for the revealed pre-images for all the validators in the `NetworkClient` class, like the following code.
`private PreImageInfo[Hash] last_preimages;`

I will create a PR for the first implementation. We can have a whiteboard while I'm implementing the in the PR.
