### ISSUE TITLE
Change the scpp logging system to use our logger instead of stdout

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#346]
### Description

Currently SCP code logs directly to stdout, see here: https://github.com/bpfkorea/agora/blob/e1351051e09ac71d2144edb03fdcd4dfad5d4b6a/source/scpp/src/util/Logging.h#L16

This code originally used the SCP logger:
https://github.com/stellar/stellar-core/blob/578b951aa027b850807fc15841a6eb2fffda611e/src/util/Logging.h

https://github.com/stellar/stellar-core/blob/578b951aa027b850807fc15841a6eb2fffda611e/src/util/Logging.cpp

However, we should change it to use our D ocean logger system instead. One approach to doing this is to provide D wrapper functions which forward logging to the ocean logger. We primarily use the ocean logger with this helper module: https://github.com/bpfkorea/agora/blob/v0.x.x/source/agora/utils/Log.d

The SCP code typically uses logging like this:

```
CLOG(ERROR, "SCP") << "not sane statement from self, skipping " 
    << "  e: " << mSlot.getSCP().envToStr(envelope);
```

This could be forwarded to a D function with an extern(C++) linkage, to a logger instantiated with `Log.lookup("SCP")` and called with `log.error(...)` on the D side.

The part to figure out is how to pass the arguments to the D side. Would it be a single string constructed on the C++ side, or a number of arguments (perhaps array of strings, variable-length arguments, etc).

Also, care needs to be taken to ensure there are no memory leaks.

### Definition of done:

- [ ] Make SCP use Ocean's logger instantiated on the D side. SCP only logs to a `"SCP"` logger, so you only need to instantiate this one logger instance for it to work.
- [ ] Different logging levels should be supported, so for example `CLOG(TRACE, ...)`  and `CLOG(ERROR, ...)` are using log.trace / log.error, etc, on the D side.
- [ ] Ensure there are no memory leaks in the SCP logging code. You might have to manually delete the C++ strings on the D side after logging.

As a bonus, it would be nice to not have any excessive memory allocations. However, we can improve on this later if it's unavoidable.

**Comment by Geod24** [comment]
This is a good issue if anyone wants to get familiar with the C++ interop side of things

**Comment by bpalaggi** [comment]
Relates to #209

**Comment by linked0** [comment]
If I had not read Andrej's desciption carefully, I would think I should have to make Ocean's logger to be able to receive function calls from C++. But it's not. I found out that the first thing I have to do is to make a logging function that the SCPP codes can call instead of the CLOG function. Is it right? Any comment would be helpful.

**Comment by AndrejMitrovic** [comment]
Yes that's the only thing that's necessary, make the SCP code use ocean's logger instead of outputting directly to stdout.

**Comment by linked0** [comment]
You mean that the SCP code can use the Ocean's logger through some logging function that I will be implementing in agora/utils/Log.d.

**Comment by AndrejMitrovic** [comment]
Sure, you can place it there. An `extern(C++)` implementation on the D side, and a function prototype on the C++ side so the C++ code can then use it.

**Comment by linked0** [comment]
There was two approaches on resolving this issue. One is to use the D variadic functions to be called from C++, and the other is to make the class called DLOG having the operator overroading functions for the '<<' operator. After I have discussed about these approaches with Andrej, I determined to resolve this issue with the second approach because the first approach has some issue related to dlang compiler.

So we can use the code as below using the DLOG class implementation.
```
DLOG(FATAL, "SCP") << "Exception processing SCP messages at "
    << mSlotIndex
    << ", envelope: " << mSCP.envToStr(envelope) << endl;
```
When the operator receives 'endl' as argument, it calls a logging function in D, and then the function of Ocean's logger is called.
There are a few thing to consider such as how a DLOG object can hand in unspecified number of parameters to the D code. 

Any Information or comments would be greatly appreciated.

**Comment by linked0** [comment]
I have changed my approach from creating a class and making it have an operator overloading for the left shift operator(<<) to just creating a log function for C++ code. It’s because the original approach using a class has too much items to be considered and it's time-consuming.
