### ISSUE TITLE
Upgrade SCPD to the latest SCP release

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#505]
There's a bunch of changes / improvements in SCP that we should adapt to.

For example the increase of the number of possible subquorums: https://github.com/stellar/stellar-core/commit/aa45d9eaa4ece2d2d6f9b2bcbdc5898ba5d18080

**Comment by Geod24** [comment]
This is blocked on testing whether the C++ support is correct, and getting the C++ definitions right (we're currently cutting corners).
Related: https://github.com/bpfkorea/agora/issues/561

**Comment by AndrejMitrovic** [comment]
Is there something specific about SCP that they're using in their master version that would complicate things when adapting to the latest version?

In the meantime, I will try to update to a slightly newer version https://github.com/stellar/stellar-core/releases/tag/v11.2.0, which is 109 commits ahead of the version we use in Agora. This release has the ability to group validators into high quality / medium quality / low quality in the quorum configuration, which will come in really handy for https://github.com/bpfkorea/agora/issues/240.

**Comment by Geod24** [comment]
https://github.com/stellar/stellar-core/pull/2369

**Comment by AndrejMitrovic** [comment]
Thanks.

**Comment by AndrejMitrovic** [comment]
This needs to be prioritized asap. ~So I will take this task the next sprint, in addition to any other work I have queued.~

Edit: sorry I didn't realize Daniel was assigned to this already. But it was not in the sprint?

**Comment by Geod24** [comment]
This needs to be prioritized, as the following issues depend on it:
- https://github.com/bpfkorea/agora/issues/982
- https://github.com/bpfkorea/agora/issues/1171
- https://github.com/bpfkorea/agora/issues/1191

The issue we're facing is that the compiler does not correctly handle passing elaborate data structure by value.
This is the tracker ID for it: https://issues.dlang.org/show_bug.cgi?id=20235

One solution for this problem is to simply revert some of the changes that were made upstream so we only take things by reference.

**Comment by Geod24** [comment]
This might also resolve https://github.com/bpfkorea/agora/issues/661

**Comment by Geod24** [comment]
Mostly done in #2065 
We're still one version behind, but the issue here was the switch from ref params to value params, which has been done.
