### ISSUE TITLE
Make the validator set restore validators' data from the chain on startup

### ISSUE THREAD

**Issue by linked0** [bosagora/agora#605]
In current implementation of the enrollment manager, there are a problem to solve. All the problems occurs when the database crashes and a node cannot restore the data for validators

The information of validator should be stored safely so that it can be restored any time like UTXO set.

Definition of Done:

- [x] Restore data of validator set such as enrollment information and the enrolled height from the chain into the validator set table.

How to implement:
- When a`ValidatorSet`(which is being split from `EnrollmentManager`) is created, it can enrollment information and enrolled height from the chain.
- The previously broadcast from a validator cannot restore from the chain in currently implemented code, so we must find the way to get preimages.

**Comment by Geod24** [comment]
A shutdown is not going to solve the problem though. We should have a recovery strategy in place.

What's causing the problem ? If it's a database error, is it because the table is corrupted ? As long as we don't loose *critical* data (such as the random value that is the root of the preimage), we can still emit those preimage.

Shutting down will *not* be expected, and while people should have a restart mechanism in place, we should not abuse it.

**Comment by AndrejMitrovic** [comment]
I suggested shutting down if the error is unrecoverable.

Now, if sqlite fails you may try to regenerate the preimage and then try to use the database again. But what guarantees do you have that you will not run into the same error as before? How many times should the node attempt to store the preimage before it gives up? If it never gives up, you risk running into an infinite loop of failed retries.

(There is an option of using error stats to trigger an alarm of sorts, in place of just shutting down. But those are unreliable too, because they use disk I/O which can fail. )

So we would need to analyze the d2sqlite bindings and see how the Exceptions are used. To find out why Exceptions can be thrown, and which errors are recoverable. In addition, the SQLite documentation needs to be consulted too.

**Comment by Geod24** [comment]
> How many times should the node attempt to store the preimage before it gives up?

[There are common answers to this problem](https://en.wikipedia.org/wiki/Exponential_backoff).

But even if the node cannot save the pre-image, the error isn't so critical that it would prevent it from making progression on the blockchain, is it ?

**Comment by AndrejMitrovic** [comment]
> There are common answers to this problem.

It was more of a rhetorical question. There is complexity when you write code which tries to recover from errors, and that code too could have bugs and error out.

But yeah in the general case if the error is recoverable, we should try to recover.

> But even if the node cannot save the pre-image, the error isn't so critical that it would prevent it from making progression on the blockchain, is it ?

I mean saving is not a critical error, indeed. But a lot of code in https://github.com/bpfkorea/agora/pull/563 logs errors and ignores those errors, there is no retry mechanism at all. Even for just **getting** a preimage, not just saving it. So we will have to improve this.

**Comment by linked0** [comment]
> Now, if sqlite fails you may try to regenerate the preimage and then try to use the database again.

If DB crashed, the preimages cannot be recovered because the seed value for making preimages is also stored in DB. We need to think about other approaches for the errors.

**Comment by linked0** [comment]
> If DB crashed, the preimages cannot be recovered because the seed value for making preimages is also stored in DB.

**Comment by linked0** [comment]
I changed the title "Make a node exit in case of not being able to sending pre-image" to "Make the validator set restore validator's data from the chain" and the description. These things are discussed in white-boarding session.

**Comment by Geod24** [comment]
So to phrase this issue differently:
When a validator starts from a clean slate and catch up with the blockchain, it should start validating again if it is already enrolled.
