### ISSUE TITLE
Use our own hashing in `getQSet`  instead of relying on Stellar's

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#702]
Currently we have this code:
https://github.com/bpfkorea/agora/blob/b20a58d39bc3ae3d9993fa9a69763bb85ea1a62b/source/agora/consensus/protocol/Nominator.d#L117-L119

This is used mostly here  (fetching it):
https://github.com/bpfkorea/agora/blob/e35e09a740e335f1d0695d7ddaa2ca0e9c4db966/source/agora/consensus/protocol/Nominator.d#L403-L409
(BTW, nice typo)

However, we don't need to use ByteSliceHasher and the likes, we can just hash things using our own `hash` function. This would avoid the underlying vector being copied also.

**Comment by AndrejMitrovic** [comment]
Can we? StellarHash is a 32-byte type, and our own hash is 64-byte.

**Comment by AndrejMitrovic** [comment]
> Can we? StellarHash is a 32-byte type, and our own hash is 64-byte.

The answer is yes we can, but we need to change the Hash definition in SCPP:

```diff
diff --git a/source/scpp/src/xdr/Stellar-types.h b/source/scpp/src/xdr/Stellar-types.h
index 28ecc823..5d989d3f 100644
--- a/source/scpp/src/xdr/Stellar-types.h
+++ b/source/scpp/src/xdr/Stellar-types.h
@@ -9,7 +9,7 @@

 namespace stellar {

-using Hash = xdr::opaque_array<32>;
+using Hash = xdr::opaque_array<64>;
 using uint256 = xdr::opaque_array<32>;
 using uint32 = std::uint32_t;
 using int32 = std::int32_t;
```

I need to do this as part of https://github.com/bpfkorea/agora/pull/621, so I'll give this a go.

**Comment by AndrejMitrovic** [comment]
Hmm there's another problem. SCP sets its own quorum set hash:

https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/scpp/src/scp/LocalNode.cpp#L27

and https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/scpp/src/scp/LocalNode.cpp#L49

The hash passed to `Nominator.getQSet` is the one generated by SCP (which uses `xdr_to_opaque`). So what `Nominator` does has to match what `LocalNode` does.

So there's two problems here:
- SCP deals with SCPQuorumSet, not QuorumConfig. That's not a big problem because we can implement hashing routines for SCPQuorumSet.
- SCP hardcodes the way hashing should be done on SCPQuorumSet. And then it expects the SCPDriver (Nominator) to use the same hashing in its constructor. This is leaky abstractions IMO. The hashing of SCPQuorumSet should be customizable..

I'm not sure about the best way to proceed. I could try to modify SCPP and declare a prototype of a hashing function which is then implemented on the D side. There's also the option of doing this upstream, but it requires careful design and the work might be rejected by Stellar.
