### ISSUE TITLE
Add the feature to change or delete enrollments stored

### ISSUE THREAD

**Issue by linked0** [bosagora/agora#742]
After storing Enrollments, there are cases when those needs to be removed or modified. So we need to find out the cases when the two functionalities are needed, to implement the functions, make them to be called. 

Definition of Done:

- [ ] If an UTXO is used in some transaction, the enrollment with that must be removed from the validator set(or the use of it must be blocked before the validator cycle ends).
- [ ] If an enrollment is not confirmed through the consensus protocol, it can be modified on addtional enrollments.

**Comment by AndrejMitrovic** [comment]
I would also add that there should be an aging period after which an enrollment is deleted from the pool. If the enrollment has been kept in the pool for over X number of blocks (we could configure this number), we should remove it from the pool. The node which wants to enroll can try to create and send a new enrollment.

This is because we don't want to store Enrollments indefinitely. It can become a form of DDoS.

**Comment by linked0** [comment]
> If the enrollment has been kept in the pool for over X number of blocks (we could configure this number)

The work item for making the aging period configurable is included in #520 .

**Comment by Geod24** [comment]
Enrollments are now tied to a specific height via their commitment to avoid replay, so this is fixed.
