### ISSUE TITLE
Avoid nominating and externalizing Enrollments that will fail Block validation

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#900]
There were several issues with nomination discovered in #899:
- [x] There were leftover `Enrollment` in the `EnrollmentPool` which were picked up to be nominated, although they were also in the `ValidatorSet`;
- [x] There is no check that the result of `Ledger.prepareNominatingSet` can in fact be nominated;
- [x] Other node achieved consensus on duplicated Enrollments (!)

All of this needs to be fixed. #899 was just a stopgap measure but nominating enrollment (and nomination in general) needs to be much more thought out.

**Comment by linked0** [comment]
The main thing of this issue is to remove the duplication of enrollments. So we need to add the following algorithm for this issue.
- We add the `requested_height` column in the `enrollment_pool` table, which means the height when the enrollment is inserted.
- If the `requested_height` of an enrollment is smaller than the `enrolled_height`, the enrollment is removed from the `EnrollmentPool` when the `getEnrollments` function of the `EnrollmentManager` is called.

All the issues to be resolved is all about the `getEnrollments` function of the `EnrollmentManager`.
It there are any other point of view or any suggestions, please let me know. I will review them positively.

**Comment by Geod24** [comment]
Last point: Do not return `Enrollment` for which the `requested_height` is > than the height we are nominating for.

**Comment by Geod24** [comment]
> We add the `requested_height` column in the `enrollment_pool` table, which means the height when the enrollment is inserted.

It should be "the height when the enrollment will be available".
