### ISSUE TITLE
Remove quorum set hashes from SCP protocol messages

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#982]
In our quorum algorithm design the quorum is always known for all the active validator nodes in the system.

Therefore sending the quorum hash in each SCP message becomes superfluous. Removing it should save quite a bit on network bandwidth too.

This should be fairly simple to do because SCP already abstracts this away in the `getQuorumSetFromStatement` function.

**Comment by AndrejMitrovic** [comment]
Another useful optimization: Instead of storing the `nodeID` we can store a `ushort` which would be the validator index. Since all messages will be signed there is no possibility of forging the message.

**Comment by linked0** [comment]
We can directly use [the code by @AndrejMitrovic](https://github.com/bosagora/agora/pull/1192) for this issue. But applying the code could be started as soon as issue #1191 is solved because we will use the validator index as `NodeID` instead of `UTXO` after issue #1191 being solved and this issue is tightly related to the `NodeID`.

**Comment by linked0** [comment]
This is solved by [PR #2325](https://github.com/bosagora/agora/pull/2353).
